name: scrcambio_app
description: "Usa la pantalla de tu dispositivo como una linterna más tenue"
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  screen_brightness: ^2.1.7
  shared_preferences: ^2.5.4
  themed: ^8.1.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
