name: Build and Release Android

on: 
  push: 
    branches: [ main ]
    tags: 
      -"v*.*.*"
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Flutter Setup
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable
      
      - name: Decode Keystore and move it to android/app
        run: |
          echo $ENCODED_STRING | base64 -di > ./android/app/release.jks
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE }}
      - name: Build APKs
        shell: bash
        run: bash ./.github/release_android.sh
        env:
          RELEASE_STOREPASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEYPASSWORD: ${{ secrets.KEY_PASSWORD }}
          RELEASE_KEYALIAS: ${{ secrets.KEY_ALIAS }}
        
      - name: Release andorid builds
        uses: softprops/action-gh-release@v2.5.0
        with:
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: v0.1.1 ##CAMBIAR ESTA VERSIÓN AL HACER EL PUSH Y TAMBIEN ACTUALIZAR EL CHANGELOG
          body_path: .github\release_body.md
          files: |
            release/Android-armeabi-v7a.apk
            release/Android-arm64-v8a.apk
            release/Android-x86-64.apk
            release/Android-universal.apk

            
