name: Build and Release Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Flutter Setup
        uses: subosito/flutter-action@v2.23.0
        with:
          channel: stable

      - name: Generar instalador Windows
        shell: pwsh
        run: .\.github\release_windows.ps1

      - name: Release Windows build
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body_path: .github/release_body.md
          files: release/Windows-x64.exe