name: Build and Release

on: 
  push: 
    branches: [ main ]
    tags: 
      -"v*.*.*"
jobs: 
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Obteniendo el último tag
        id: tag
        uses: 32teeth/action-github-tag@v1.0.7

      - name: Flutter Setup
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable

      - name: Check Flutter version
        run: flutter --version

      - name: build_release.ps1 para generar y renombrar builds
        shell: pwsh
        env: 
          KEYSTORE_ANDROID: ${{ secrets.ANDROID_KEYSTORE}}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD}}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
        run: powershell -File .\.github\build_release.ps1
        
      - name: Release builds
        uses: softprops/action-gh-release@v2.5.0
        with:
          #Por alguna razón no quiere obtener el tag, a pesar de que el workflow ocurre cuando se hace un push etiquetado
          #Pero vale, obtener el último tag entonces.
          tag_name: ${{steps.tag.outputs.tag}}
          body_path: .github\release_body.md
          prerelease: true
          files: |
            build/app/outputs/flutter-apk/Android-universal.apk
            build/app/outputs/flutter-apk/Android-arm64-v8a.apk
            build/app/outputs/flutter-apk/Android-x86-64.apk
            build/app/outputs/flutter-apk/Android-armeabi-v7a.apk
            build/windows/x64/runner/Release/Windows-x64.zip

            
